name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: g++ $(find . -name "*.cpp" | head -n 1) -o app

    - name: Run
      run: ./app